name: ClaudeMachineLauncher

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    from: "1.0.0"

targets:
  ClaudeMachineLauncher:
    type: application
    platform: iOS
    sources: [ClaudeMachineLauncher]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.claudemachinelauncher
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - package: SwiftTerm
        product: SwiftTerm

  ClaudeMachineLauncherTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ClaudeMachineLauncherTests]
    dependencies: 
      - target: ClaudeMachineLauncher
    settings:
      GENERATE_INFOPLIST_FILE: YES
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"

schemes:
  ClaudeMachineLauncher:
    build:
      targets:
        ClaudeMachineLauncher: all
        ClaudeMachineLauncherTests: [test]
    test:
      targets: [ClaudeMachineLauncherTests]